# shellcheck disable=SC2034
#### How this conf file works
# Use '_' to open a variable if it depends on something else
# You can modify anything but need to make sure its a valid value
# But the basic config by default should be the "smallest" working example

#### Initial bootstrap
# -r repo-url -i init-system -s seat-manager mountpoint
# Example: Use archived repo for reproducible builds
# Leave empty uses fastest mirror
MIRROR_URL=""
# MIRROR_URL="https://archive.artixlinux.org/repos/2026/03/31/"

TARGET_INI="openrc"     # openrc, runit, s6, dinit
SEAT_MGR="seatd"        # seatd, elogind
## End bootstrap

TARGET_HOOKS="HOOKS=(base udev autodetect modconf block keyboard keymap consolefont filesystems fsck)"

TARGET_BL="grub"        # efistub, limine, refind CURRENTLY GRUB ONLY
TARGET_FS="ext4"        # Filesystem: ext4, xfs, f2fs
EFI_SIZE="1GiB"         # Any value
ROOT_SIZE="4GiB"        # Root partition size (ignored if not building tmp img -> Uses 100%)

#### Side
ELEV="sudo"             # sudo, opendoas

VCONSOLE_KB="us"
VCONSOLE_FONT="default8x16"    # any font from /usr/share/kbd/consolefonts, e.g. cyr-sun16
# terminus-font needs to be added in extra for "ter" fonts

TARGET_TIMEZONE="Europe/Paris"
TARGET_HOSTNAME="vasex"
TARGET_LOCALE="en_US.UTF-8"

KERNEL="linux"          # Options: linux, linux-lts, linux-zen, linux-hardened
_KHEADERS=1             # 0=do not download headers

## AUR
GRIMAUR=0				# copies grimaur and python git base-devel into target
# Note currently base-devel pulls in sudo by default...

### HW
FW="linux-firmware"     # general or linux-specific
HW_CPU="intel-ucode"	# amd-ucode

PPD=0 			# power profiles (uses polkit)

ZRAM_SIZE="4G"
ZRAM_ALGO="zstd"        # zstd, lz4, lzo, deflate
VM_SWAPPINESS=100
VM_WATERMARK_BOOST=0
VM_WATERMARK_SCALE=125

NETWORK="dhcpc"         # nm (NetworkManager), nm-iwd (NM + iwd backend), iwd-only (iwd native DHCP), iwd-dhcpc (iwd+dhcpcd), dhcpc (dhcpcd only)
### Notably any NM will pull in polkit, if you want the minimal seatd route pick iwd-only or iwd-dhcpc

DNS1="8.8.8.8"
DNS2="8.8.4.4"

### Could add a IpV6 option here

### Secu
LOCK_ROOT=1             # 0=keep root login enabled, 1=lock root account

### Personals
EDITOR="vim"         				    # neovim, micro, nano
EXTRAS="jq pacman-contrib"				# for you to add additional packages

### HW
HW_GPU=""
HW_SOUND=""

#### ILLUSTRATIVE EXAMPLES

# # AMD/ATI Graphics (Open-Source)
# AMD="mesa xf86-video-amdgpu xf86-video-ati vulkan-radeon"
#
# # Intel Graphics (Open-Source)
# INTEL="mesa intel-media-driver vulkan-intel"
# "libva-intel-driver" for legacy
#
# # Nvidia mainline kernel (linux) - no DKMS [world]
# NVIDIA="nvidia-open nvidia-utils nvidia-utils-openrc"
#
# # Nvidia other kernel (linux-something) - DKMS [world]
# NVIDIA="nvidia-open-dkms dkms nvidia-utils nvidia-utils-openrc"
#
# # Nvidia 580xx branch (linux) - no DKMS [world]
# NVIDIA="nvidia-580xx nvidia-580xx-utils nvidia-utils-openrc"
#
# # Nvidia 580xx branch (linux-something) - DKMS [world]
# NVIDIA="nvidia-580xx-dkms dkms nvidia-580xx-utils nvidia-utils-openrc"
# 
# ... More versions or specifc drivers are possible to find.
# https://packages.artixlinux.org/packages/ 
# and do look up your own hardware :)
#
# # Nvidia Open-Source - Nouveau [world]
# NVIDIA="mesa xf86-video-nouveau vulkan-nouveau"
#
# # Hybrid Graphics (Intel/AMD + Nvidia mobile) iGPU + dGPU
# add "nvidia-prime" for switching [world]
#
# # Virtual Machine - QEMU/KVM
# QEMU="mesa vulkan-virtio qemu-guest-agent"
#
# # Virtual Machine - Software renderer
# VBOX="mesa virtualbox-guest-utils"
#
# # Audio Firmware - SOF (Sound Open Firmware)
# AUDIO="sof-firmware"
#
# # Audio Firmware - ALSA
# AUDIO="alsa-firmware"
