#### How this conf file works
# Use '_' to open a variable if it depends on something else
# You can modify anything but need to make sure its a valid value
# But the basic config by default should be the "smallest" working example 

#### Initial bootstrap
# -r repo-url -i init-system -s seat-manager mountpoint
# Example: Use archived repo for reproducible builds
# Leave empty uses fastest mirror
MIRROR_URL="https://mirror1.artixlinux.org/repos"
# MIRROR_URL="https://archive.artixlinux.org/repos/2026/03/31/"

TARGET_INI="openrc"     # openrc, runit, s6, dinit
SEAT_MGR="seatd"        # seatd, elogind
## End bootstrap

TARGET_HOOKS="HOOKS=(base udev autodetect modconf block keyboard keymap consolefont filesystems fsck)"

TARGET_BL="grub"        # efistub, limine, refind CURRENTLY GRUB ONLY 
TARGET_FS="ext4"        # Filesystem: ext4, btrfs, xfs, f2fs
EFI_SIZE="1GiB"         # Any value
ROOT_SIZE="4GiB"        # Root partition size (ignored if not building tmp img -> Uses 100%)

#### Side
ELEV="doas"             # sudo, opendoas
VCONSOLE_KB="us"
VCONSOLE_FONT="default8x16"    # any font from /usr/share/kbd/consolefonts, e.g. cyr-sun16
# terminus-font needs to be added in extra for "ter" fonts

TARGET_TIMEZONE="Europe/Paris"
TARGET_HOSTNAME="vasex"
TARGET_LOCALE="en_US.UTF-8"

KERNEL="linux"          # Options: linux, linux-lts, linux-zen, linux-hardened
_KHEADERS=1             # 0=do not download headers

### HW
FW="linux-firmware"     # general or linux-specific
HW_CPU="intel-ucode"	# amd-ucode

ZRAM_SIZE="4G"
ZRAM_ALGO="zstd"        # zstd, lz4, lzo, deflate
VM_SWAPPINESS=100
VM_WATERMARK_BOOST=0
VM_WATERMARK_SCALE=125

NETWORK="dhcpc"         # nm (NetworkManager), nm-iwd (NM + iwd backend), iwd-dhcpc (standalones wifi + eth), dhcpc (standalone eth only)
### Notably any NM will pull in polkit, if you want the minimal seatd route pick iwd and/or dhcpd

DNS1="8.8.8.8"
DNS2="8.8.4.4"

### Secu
LOCK_ROOT=0             # 0=keep root login enabled, 1=lock root account

### Personals
EDITOR="vim"         				    # neovim, micro, nano
EXTRAS="jq pacman-contrib"				# for you to add additional packages

### HW
HW_GPU=""
HW_SOUND=""

#### ILLUSTRATIVE EXAMPLES / SOME MIGHT REQUIRE AUR POST-BOOT
# # AMD/ATI Graphics (Open-Source)
# HW_AMD_OPENSOURCE="mesa xf86-video-amdgpu xf86-video-ati vulkan-radeon"
# 
# # Intel Graphics (Open-Source)
# HW_INTEL_OPENSOURCE="mesa libva-intel-driver vulkan-intel"
# 
# # Nvidia Graphics - Proprietary Driver
# HW_NVIDIA_PROPRIETARY="nvidia-dkms dkms"
# 
# # Nvidia Graphics - Open Kernel Module (Turing+)
# HW_NVIDIA_OPEN_KERNEL="nvidia-open-dkms dkms"
# 
# # Nvidia Graphics - Open-Source (Nouveau)
# HW_NVIDIA_OPENSOURCE="mesa xf86-video-nouveau vulkan-nouveau"
# 
# # Hybrid Graphics - Nvidia Prime (Intel + Nvidia) iGPU + dGPU
# HW_NVIDIA_PRIME="nvidia-prime"
# 
# # Virtual Machine - QEMU/KVM
# HW_VM_QEMU="mesa vulkan-virtio qemu-guest-agent vulkan-swrast"
# 
# # Virtual Machine - Software renderer
# HW_VM_VIRTUALBOX="mesa vulkan-swrast virtualbox-guest-utils"
# 
# # Audio Firmware - SOF (Sound Open Firmware)
# HW_AUDIO_SOF="sof-firmware"
# 
# # Audio Firmware - ALSA
# HW_AUDIO_ALSA="alsa-firmware"
