#### How this conf file works
# Use '_' to open a variable if it depends on something else

#### Main
# Example: Use archived repo for reproducible builds
# Leave empty uses fastest mirror
MIRROR_URL=""
# MIRROR_URL="https://archive.artixlinux.org/repos/2025/11/01"

TARGET_INI="openrc"     # openrc, runit, s6, dinit
## End bootstrap

TARGET_HOOKS="HOOKS=(base udev autodetect modconf block keyboard keymap consolefont filesystems fsck)"

TARGET_BL="grub"        # efistub, limine, refind CURRENTLY GRUB ONLY 
TARGET_FS="ext4"        # Filesystem: ext4, btrfs, xfs, f2fs
EFI_SIZE="1GiB"         # Any value
ROOT_SIZE="4GiB"        # Root partition size

#### Side
ELEV="sudo"             # sudo, opendoas
EDITOR="vim"            # neovim, micro, nano
VCONSOLE_KB="us"
VCONSOLE_FONT="default8x16"    # TODO: terminus-fonts condition
TARGET_TIMEZONE="Europe/Paris"
TARGET_HOSTNAME="vasex"
TARGET_LOCALE="en_US.UTF-8"

KERNEL="linux"          # Options: linux, linux-lts, linux-zen, linux-hardened
_KHEADERS=1             # 0=do not download headers

FW="linux-firmware"     # linux-specific

ZRAM_SIZE="4G"
ZRAM_ALGO="zstd"        # zstd, lz4, lzo, deflate
VM_SWAPPINESS=100
VM_WATERMARK_BOOST=0
VM_WATERMARK_SCALE=125

NETWORK="iwd"        # nm (NetworkManager), nm-iwd (NM + iwd backend), iwd (standalone), TODO: (connman)
### Notably any NM will pull in polkit, if you want the minimal seatd route pick iwd + dhcpd alone
DNS1="8.8.8.8"
DNS2="8.8.4.4"

### Secu
SEAT_MGR="seatd"        # seatd, elogind
LOCK_ROOT=1             # 0=keep root login enabled, 1=lock root account
USE_UFW=1               # 0=skip fw setup
