#!/bin/bash
# requires pacman-contrib

for pkg in $(pacman -Qqe); do                                                                                                                                                                                                             
    count=$(pactree -u "$pkg" 2>/dev/null | wc -l)                                                                                                                                                                                        
    echo "$((count - 1)) $pkg"                                                                                                                                                                                                            
done | sort -rn | head -20