name: shellcheck

on:
  push:
    paths:
      - '**.sh'
      - '**.conf'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run shellcheck on scripts
        run: |
          shellcheck --severity=warning *.sh artix-bootstrap/*.sh
          shfiles=$(find src -name '*.sh' 2>/dev/null)
          [ -n "$shfiles" ] && shellcheck --severity=warning $shfiles || true

      - name: Run shellcheck on conf
        run: shellcheck --shell=bash --severity=warning *.conf
